# SonarCloud configuration
# https://sonarcloud.io/project/overview?id=aruanoguate_json-treesize

sonar.projectKey=aruanoguate_json-treesize
sonar.organization=aruanoguate

sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,*.vsix

# TypeScript / JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
